---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
  - ["private_network", {ip: "192.168.33.34"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[cloudmux::default]
    attributes:
